# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20161122_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
